mode = "dark"

accent = "#2f8ca3"
selection = "#2f8ca3"
muted = "#193f4a"

background = "#0D1517"
dark_background = "#080D0E"
darker_background = "#030504"
lighter_background = "#193f4a"

foreground = "#2F8CA3"
dark_foreground = "#236A7A"
light_foreground = "#55B5C9"
bright_foreground = "#8DE8F5"

red = "#2F8CA3"
yellow = "#2F8CA3"
orange = "#2F8CA3"
green = "#2F8CA3"
cyan = "#2F8CA3"
blue = "#2F8CA3"
magenta = "#2F8CA3"
brown = "#2F8CA3"

bright_red = "#2F8CA3"
bright_yellow = "#2F8CA3"
bright_green = "#2F8CA3"
bright_cyan = "#2F8CA3"
bright_blue = "#2F8CA3"
bright_magenta = "#2F8CA3"
